name: Blog Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        npm install
        npm run build
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        path: gh-pages-pre
        ref: gh-pages
        fetch-depth: 0
    - name: Publish to gh-pages 🚀
      env:
        TZ: Asia/Shanghai
      run: |
        mv /public gh-pages
        cp -r gh-pages-pre/.git gh-pages/
        cd gh-pages
        git config --local user.email "tsejx@foxmail.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto Delopy at `date +"%Y-%m-%d %H:%M"`"
        git push origin gh-pages